"use client";

export default function TermsAndConditions() {
  return (
    <section className="min-h-screen bg-white dark:bg-slate-950 text-slate-800 dark:text-slate-200 py-16 px-6">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-4xl font-bold mb-4">Terms & Conditions</h1>

        <p className="text-sm text-slate-500 dark:text-slate-400 mb-10">
          Last Updated: July 23, 2026
        </p>

        <div className="space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="leading-7">
              By accessing or using GrammarCheckerAI, you agree to comply with
              these Terms & Conditions. If you do not agree with any part of
              these terms, please discontinue using our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              2. Our Services
            </h2>
            <p className="leading-7">
              GrammarCheckerAI provides AI-powered grammar correction, spelling
              checks, writing improvements, readability suggestions, and other
              language assistance tools. The results are generated by artificial
              intelligence and may not always be completely accurate.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              3. User Responsibilities
            </h2>

            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate information when creating an account.</li>
              <li>Keep your login credentials secure.</li>
              <li>Use the service only for lawful purposes.</li>
              <li>Do not attempt to misuse, hack, or disrupt the platform.</li>
              <li>Do not upload harmful, illegal, or malicious content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              4. User Content
            </h2>
            <p className="leading-7">
              You retain ownership of any text you submit. By using our service,
              you grant us permission to process your content solely for
              providing grammar corrections and AI-generated suggestions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              5. Intellectual Property
            </h2>
            <p className="leading-7">
              All website content, including logos, branding, design, source
              code, graphics, and features, is the property of GrammarCheckerAI
              unless otherwise stated. Unauthorized copying or redistribution is
              prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              6. AI Disclaimer
            </h2>
            <p className="leading-7">
              AI-generated suggestions are provided for informational and
              educational purposes only. You are responsible for reviewing and
              verifying all generated content before using it in professional,
              academic, or legal situations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              7. Account Termination
            </h2>
            <p className="leading-7">
              We reserve the right to suspend or terminate accounts that violate
              these Terms & Conditions or engage in activities that may harm our
              platform or other users.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              8. Limitation of Liability
            </h2>
            <p className="leading-7">
              GrammarCheckerAI is provided &quot;as is&quot; without warranties of any
              kind. We are not responsible for any direct, indirect, incidental,
              or consequential damages arising from your use of the platform or
              reliance on AI-generated results.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              9. Third-Party Services
            </h2>
            <p className="leading-7">
              Our platform may integrate third-party services such as AI
              providers, analytics tools, authentication services, or cloud
              storage. Your use of those services may also be subject to their
              respective terms and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              10. Changes to the Terms
            </h2>
            <p className="leading-7">
              We may update these Terms & Conditions at any time. Continued use
              of the website after changes become effective constitutes your
              acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              11. Governing Law
            </h2>
            <p className="leading-7">
              These Terms & Conditions shall be governed and interpreted in
              accordance with the laws of your applicable jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">
              12. Contact Us
            </h2>

            <p className="leading-7">
              If you have any questions regarding these Terms & Conditions,
              please contact us.
            </p>

            <div className="mt-4 rounded-xl border border-slate-200 dark:border-slate-800 p-5">
              <p>
                <strong>GrammarCheckerAI</strong>
              </p>
              <p>Email: grammarcheckerai46@gmail.com</p>
              <p>Website: https://grammarcheckerai.vercel.app</p>
            </div>
          </section>
        </div>
      </div>
    </section>
  );
}